version: '3.2'

services:
  client-node:
    image: game_client:latest
    container_name: game-client
    restart: always
    ports:
      - 3000:3000
    networks:
      game_network:

  server-node:
    image: game_server:latest
    container_name: game-server
    restart: always
    ports:
      - 7000:7000
    networks:
      game_network:

networks:
  game_network:
    driver: 'bridge'
